/**
 * In-memory sample data mirroring supabase/seed.sql, for previewing the UI with
 * WELLWATCH_FIXTURES=1 and no Supabase project. Never active in production.
 */
import type { WellPage } from "./data";
import type { MyWellRow, Profile } from "./types";

export const fixturesEnabled = () =>
  process.env.WELLWATCH_FIXTURES === "1" && process.env.NODE_ENV !== "production";

export const fixtureProfile: Profile = {
  id: "10000000-0000-0000-0000-000000000011",
  email: "funder.one@example.com",
  display_name: "Margaret Chen",
  role: "funder",
  organization_id: null,
  notify_email: true,
};

const kyabirwa: WellPage = {
  well: {
    id: "20000000-0000-0000-0000-000000000001",
    code: "UG-2026-014",
    name: "Kyabirwa",
    country: "UG",
    region: "Jinja District",
    village: "Kyabirwa",
    approx_lat: 0.4855,
    approx_lng: 33.1912,
    status: "handover",
    well_type: "hand_drilled",
    program_name: "2026 Hand Drilled Well Program, Uganda",
    sponsor_line: "the Chen family, Australia",
    people_served: 1050,
    households: 176,
    depth_m: "40.0",
    yield_lph: 1200,
    source_type: "Borehole with India Mark II hand pump",
    pump_type: "India Mark II",
    contractor: "Suubi drilling crew",
    gps_text: "N 0.730133, E 32.965788",
    dedication: "In memory of Robert Chen",
    summary: "A farming village on the east bank of the Nile, 45 minutes from the tarmac.",
    before_story: "Until now the nearest clean water was more than 4 km away. Women and children collected water from a swamp shared with livestock, leaving before dawn and often missing school or work. Typhoid and diarrhoea were common in children under twelve.",
    before_distance_km: "4",
    after_distance_m: 300,
    hours_saved_day: "2",
    impacts: "Walk to clean water cut from 4 km to about 300 m\nWomen and girls save around two hours every day\nFewer cases of diarrhoea and typhoid in children under 12\nMore girls attending Kyabirwa Primary regularly\nLess back and neck pain from carrying jerrycans",
    wuc_members: 8,
    wuc_women: 4,
    wuc_youth: 2,
    wuc_pwd: 1,
    wuc_treasurer_woman: true,
    training_note: "An eight-member Water User Committee was formed and trained by Suubi in pump care, monthly greasing and inspection, and in collecting a small user fee for repairs. The whole village took part in WASH training: clean containers, boiling, latrines and hand-washing.",
    sustainability: "Suubi returns for follow-up monitoring visits and the committee keeps a repair fund. Three residents can do routine maintenance themselves.",
    challenges: "Heavy rain in the second week made the access road impassable for two days; the crew camped on site.",
    lessons: null,
    plaque_installed: true,
    completed_at: "2026-07-19",
    report_file_id: null,
    partner_org_id: "30000000-0000-0000-0000-000000000001",
    drive_folder_id: null,
    folder_is_public: true,
    target_cost: "9800",
    currency: "AUD",
    updated_at: "2026-07-19T00:00:00Z",
  },
  stages: [
    { stage: "funded", reached_at: "2026-06-15", expected_at: null, note: null },
    { stage: "survey", reached_at: "2026-06-24", expected_at: null, note: "Hydrogeological survey; site chosen beside the school" },
    { stage: "drilling", reached_at: "2026-07-06", expected_at: null, note: "Water struck at 42 m, drilled to 48 m" },
    { stage: "pump_apron", reached_at: "2026-07-11", expected_at: null, note: null },
    { stage: "water_flowing", reached_at: "2026-07-12", expected_at: null, note: "Yield test 1,200 L/h" },
    { stage: "handover", reached_at: "2026-07-19", expected_at: null, note: "Water committee of 7 trained; 4 women" },
  ],
  updates: [
    {
      id: "u4", stage: "handover", source: "drive", happened_at: "2026-07-19T11:00:00Z",
      body: "Handover ceremony. The water committee (four women, three men) has been trained on pump maintenance and will collect a small monthly fee for repairs.",
      media: [
        { id: "m6", drive_file_id: "seed-kyabirwa-hand-1", kind: "photo", mime: "image/jpeg", name: "IMG_4210.jpg", width: 1600, height: 1200, duration_s: null, taken_at: "2026-07-19T10:20:00Z", caption: "Inauguration day", tag: "inauguration" },
        { id: "m7", drive_file_id: "seed-kyabirwa-hand-2", kind: "photo", mime: "image/jpeg", name: "IMG_4215.jpg", width: 1600, height: 1200, duration_s: null, taken_at: "2026-07-19T10:45:00Z", caption: "The acknowledgement plaque on the pump head", tag: "plaque" },
      ],
    },
    {
      id: "u3", stage: "water_flowing", source: "drive", happened_at: "2026-07-12T08:00:00Z",
      body: "First clean water. Yield test came back at 1,200 litres an hour, more than enough for the whole village.",
      media: [{ id: "m5", drive_file_id: "seed-kyabirwa-water-1", kind: "photo", mime: "image/jpeg", name: "IMG_4160.jpg", width: 1600, height: 1200, duration_s: null, taken_at: "2026-07-12T07:30:00Z", caption: null, tag: null }],
    },
    {
      id: "u2", stage: "drilling", source: "drive", happened_at: "2026-07-06T12:30:00Z",
      body: "Rig arrived at 7am. Hit water at 42 metres — big cheer from everyone watching.",
      media: [
        { id: "m2", drive_file_id: "seed-kyabirwa-drill-1", kind: "photo", mime: "image/jpeg", name: "IMG_4102.jpg", width: 1600, height: 1200, duration_s: null, taken_at: "2026-07-06T05:10:00Z", caption: null, tag: null },
        { id: "m3", drive_file_id: "seed-kyabirwa-drill-2", kind: "photo", mime: "image/jpeg", name: "IMG_4117.jpg", width: 1200, height: 1600, duration_s: null, taken_at: "2026-07-06T11:55:00Z", caption: null, tag: null },
        { id: "m4", drive_file_id: "seed-kyabirwa-drill-v1", kind: "video", mime: "video/mp4", name: "VID_4118.mp4", width: 1280, height: 720, duration_s: 42, taken_at: "2026-07-06T12:02:00Z", caption: null, tag: null },
      ],
    },
    {
      id: "u1", stage: "survey", source: "admin", happened_at: "2026-06-24T07:00:00Z",
      body: "Survey team walked the site with the village committee today. The borehole will go beside the primary school so the children can drink before class.",
      media: [{ id: "m1", drive_file_id: "seed-kyabirwa-survey-1", kind: "photo", mime: "image/jpeg", name: "IMG_4021.jpg", width: 1600, height: 1200, duration_s: null, taken_at: "2026-06-24T06:40:00Z", caption: "The swamp families used before", tag: "before" }],
    },
  ],
  costs: [
    { category: "drilling", amount: "5200", currency: "AUD", note: null },
    { category: "pump", amount: "1650", currency: "AUD", note: null },
    { category: "apron_platform", amount: "900", currency: "AUD", note: null },
    { category: "training", amount: "650", currency: "AUD", note: null },
    { category: "transport", amount: "800", currency: "AUD", note: null },
    { category: "monitoring", amount: "600", currency: "AUD", note: null },
  ],
  waterTests: [
    { tested_at: "2026-07-14", ph: "6.9", turbidity_ntu: "1.2", e_coli_cfu: 0, fluoride_mgl: "0.4", arsenic_ugl: "1.0", passed: true, lab: "NWSC Jinja laboratory", note: null },
  ],
  funding: { amount: "6000", currency: "AUD", funded_at: "2026-06-02", is_primary: true },
  cofunders: 2,
  partner: {
    id: "30000000-0000-0000-0000-000000000001",
    name: "Suubi Community Projects Uganda",
    country: "UG",
    intro: "A registered community-based organisation working on a self-help model. Over twelve years Suubi has built or repaired more than 500 boreholes with BridgIT.",
    contact_name: "Steven Beingana",
    contact_title: "Director",
    website: null,
    logo_file_id: null,
  },
  testimonials: [
    { id: "t1", name: "Susan", age: 13, role: "P7 candidate, Kyabirwa Primary", quote: "I used to leave home at five in the morning to reach the swamp before school. Now I fetch water in ten minutes and I have time to revise for my exams.", photo_file_id: null, sort: 0 },
    { id: "t2", name: "Imelda", age: 32, role: "Mother of three, shopkeeper", quote: "I closed my shop every afternoon to go for water and lost customers. The well is right here now. We will pay our small fee so it never breaks down.", photo_file_id: null, sort: 1 },
  ],
};

const mtenje: WellPage = {
  well: {
    id: "20000000-0000-0000-0000-000000000005",
    code: "MW-2026-032",
    name: "Mtenje",
    country: "MW",
    region: "Salima District",
    village: "Mtenje",
    approx_lat: -13.781,
    approx_lng: 34.455,
    status: "funded",
    well_type: "refurbished",
    program_name: "2026 Rural Borewell Restoration Program, Malawi",
    sponsor_line: null,
    people_served: 1650,
    households: 275,
    depth_m: null,
    yield_lph: null,
    source_type: "Borehole with Afridev pump",
    pump_type: "Afridev",
    contractor: null,
    gps_text: null,
    dedication: null,
    summary: "Inland farming village on the edge of the Nkhotakota Wildlife Reserve.",
    before_story: "The village borehole has broken down repeatedly since 2002. Families walk more than 3 km to a stream inside the reserve, sharing the water with elephants.",
    before_distance_km: "3",
    after_distance_m: null,
    hours_saved_day: null,
    impacts: null,
    wuc_members: null,
    wuc_women: null,
    wuc_youth: null,
    wuc_pwd: null,
    wuc_treasurer_woman: null,
    training_note: null,
    sustainability: null,
    challenges: null,
    lessons: null,
    plaque_installed: false,
    completed_at: null,
    report_file_id: null,
    partner_org_id: null,
    drive_folder_id: null,
    folder_is_public: true,
    target_cost: "8900",
    currency: "AUD",
    updated_at: "2026-08-18T00:00:00Z",
  },
  stages: [
    { stage: "funded", reached_at: "2026-08-18", expected_at: null, note: null },
    { stage: "survey", reached_at: null, expected_at: "2026-09-15", note: null },
  ],
  updates: [],
  costs: [],
  waterTests: [],
  funding: { amount: "8900", currency: "AUD", funded_at: "2026-08-18", is_primary: true },
  cofunders: 1,
  partner: null,
  testimonials: [],
};

export const fixtureWells: Record<string, WellPage> = { [kyabirwa.well.code]: kyabirwa, [mtenje.well.code]: mtenje };

export const fixtureMyWells: MyWellRow[] = Object.values(fixtureWells).map((p) => ({
  id: p.well.id,
  code: p.well.code,
  name: p.well.name,
  country: p.well.country,
  region: p.well.region,
  status: p.well.status,
  well_type: p.well.well_type,
  people_served: p.well.people_served,
  households: p.well.households,
  approx_lat: p.well.approx_lat,
  approx_lng: p.well.approx_lng,
  updated_at: p.well.updated_at,
  amount: p.funding?.amount ?? null,
  funded_currency: p.funding?.currency ?? "AUD",
  funded_at: p.funding?.funded_at ?? null,
  is_primary: true,
  last_update_at: p.updates[0]?.happened_at ?? null,
  cover_file_id: p.updates.flatMap((u) => u.media).find((m) => m.kind === "photo")?.drive_file_id ?? null,
}));
